web/core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path, re_path
from django.conf.urls.static import static
from page.views import Page
from events.admin import event_admin_site

urlpatterns = [
    path('entity-admin/', admin.site.urls),
    path('event-admin/', event_admin_site.urls),
    re_path(r'(?P<slug>[0-9a-z.\-\[\]]+)/$', Page.as_view(), name='page'),
    path('', Page.as_view(), {'slug': '/'}, name='home'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

web/page/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.template.defaultfilters import slugify
from unidecode import unidecode


class PagePublic(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=True)


# Create your models here.
class Page(models.Model):
    objects = models.Manager()
    page_public = PagePublic()

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Время добавления'),
        help_text=_('Время добавления'),
    )
    name = models.CharField(
        verbose_name='Название страницы',
        help_text='Название страницы',
        blank=False,
        max_length=150,
    )
    slug = models.CharField(
        verbose_name='Url страницы',
        help_text='Url страницы',
        blank=True,
        default=False,
        max_length=250,
    )
    status = models.BooleanField(
        verbose_name='Статус',
        help_text='Статус активна/скрыта',
        default=False,
    )
    title_tag = models.TextField(
        verbose_name='Тег Title',
        help_text='Тег Title',
        blank=False,
        max_length=150,
    )
    meta_tag_description = models.TextField(
        verbose_name='Тег Description',
        help_text='Тег Description',
        blank=False,
        max_length=300,
    )
    meta_tag_keywords = models.TextField(
        verbose_name='Тег Keywords',
        help_text='Тег Keywords',
        blank=False,
        max_length=5000,
    )
    template = models.CharField(
        verbose_name=_('Название шаблона'),
        help_text=_('Название шаблона'),
        blank=True,
        max_length=30,
    )

    def __str__(self):
        return ''.join((str(self.name)))

    def save(self, *args, **kwargs):
        if self.slug is not '/' and self.slug is '':
            self.slug = slugify(unidecode(self.name))
        super(Page, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _('Страницы')
        verbose_name_plural = _('Страницы')


class Content(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Время добавления'),
        help_text=_('Время добавления'),
    )
    name = models.CharField(
        verbose_name=_('Заголовок'),
        help_text=_('Заголовок'),
        blank=False,
        max_length=250,
    )
    status = models.BooleanField(
        verbose_name=_('Статус'),
        help_text=_('Статус активно/скрыто'),
        default=False,
    )
    content = models.TextField(
        verbose_name=_('Содержимое'),
        help_text=_('Содержимое'),
        blank=False,
        max_length=50000,
    )
    page = models.ForeignKey(
        Page,
        on_delete=models.CASCADE,
        verbose_name=_('Страницы'),
        help_text=_('Страницы'),
    )
    order = models.IntegerField(
        verbose_name=_('Сортировка'),
        help_text=_('Сортировка'),
        blank=False,
        default=0,
    )

    class Meta:
        verbose_name = _('Содержимое')
        verbose_name_plural = _('Содержимое')

web/page/templates/index.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
<div class="w3-green w3-center w3-padding-16">
    <h1>W3.CSS<br>Faster and Better<br>Fully Responsive CSS</h1>
    <p>{{ page.content_set.get.content }}</p>
    <div id="main-root"></div>
</div>
{% endblock %}

{% block react %}
    {% if debug %}
        <script type="text/javascript" src="{% static 'js/vendors~main.bundle.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bundle.js' %}"></script>
    {% else %}
        <script type="text/javascript" src="{% static 'js/bundle.js' %}"></script>
    {% endif %}
{% endblock react %}

web/page/templates/layout.html
{% spaceless %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ page.title_tag }}</title>
    <meta name="description" content="{{ page.meta_tag_description }}">
    <meta name="keywords" content="{{ page.meta_tag_keywords }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/favicon.ico" type="image/gif" sizes="16x16">

    {% block stylesheets %}
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% endblock stylesheets %}

    {% block javascript %}
    {% endblock javascript %}

    {% include "./google-analytics.html" %}
    {% include "./ya-counter.html" %}

</head>

<body>
    {% include './navigation.html' %}
    {% include './sidebar.html' %}

    {% block content %}
    {% endblock content %}

    {% block javascript-after %}
    <script src="{% static 'js/index.js' %}"></script>
    {% endblock javascript-after %}

    {% block react %}
    {% endblock react %}

    <!-- Footer -->
    <footer class="w3-center w3-light-grey w3-padding-32">
        <p>Powered by <a href="https://www.djangoproject.com/" title="Django" target="_blank" class="w3-hover-text-green">Django</a>&nbsp;<a
                href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-text-green">w3.css</a>
        </p>
    </footer>

</body>

</html>
{% endspaceless %}

web/page/templates/navigation.html
{% with "http://w3schools.com/w3css" as w3Uurl %}
<div class="topnav" id="myTopnav">
    <a href="/" class="active">Home</a>
    <a href="{{ w3Uurl }}/tryit.asp?filename=tryw3css_templates_gourmet_catering&amp;stacked=h" target="_blank">Demo 1</a>
    <a href="{{ w3Uurl }}/tryit.asp?filename=tryw3css_templates_band&amp;stacked=h" target="_blank">Demo 2</a>
    <a href="{{ w3Uurl }}/tryit.asp?filename=tryw3css_templates_wedding&amp;stacked=h" target="_blank">Demo 3</a>
    <a href="{{ w3Uurl }}/tryit.asp?filename=tryw3css_templates_parallax" target="_blank">Demo 4</a>
    <a class="w3-right" href="/admin" target="_blank">Admin</a>
    <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        <i class="fa fa-bars"></i>
    </a>
</div>
{% endwith %}